image: gradle:4.8.1-jdk8

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - cd TourGuide
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  script: gradle build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

  artifacts:
    paths:
      - $CI_PROJECT_DIR/generatedFiles/tourGuide.jar

test:
  stage: test
  script: gradle test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - test
      - .gradle
  artifacts:
    paths:
      - $CI_PROJECT_DIR/generatedFiles/index.html



