image: gradle:4.8.1-jdk8

stages:
  - build
  - test
  - documentation

cache:
  paths:
    - build
    - .gradle

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - cd TourGuide
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

 
assemble:
  stage: build
  script: gradle assemble

bootJar:
  stage: build
  script: gradle --build-cache bootJar
  artifacts:
    paths:
      - tourGuide-1.0.0.jar

test:
  stage: test
  script: gradle test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
     
testReport:
  stage: test
  script: gradle jacocoTestReport
  artifacts:
    paths:
      - build/jacocoHtml/index.html

javadoc:
  stage: documentation
  script: gradle javadoc
  artifacts:
    paths:
      - build/docs/javadoc/tourGuide/*