image: gradle:4.8.1-jdk8

stages:
  - build
  - test
  - documentation

cache:
  paths:
    - build
    - .gradle

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - cd TourGuide
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

 
assemble:
  stage: build
  script: gradle assemble

bootJar:
  stage: build
  script: gradle --build-cache bootJar
  artifacts:
    paths:
      - $CI_PROJECT_DIR/TourGuide/build/libs/tourGuide-1.0.0.jar

test:
  stage: test
  script: gradle test
  artifacts:
    when: always
    reports:
      junit: $CI_PROJECT_DIR/TourGuide/build/reports/tests/test
     
testReport:
  stage: test
  script: gradle jacocoTestReport
  artifacts:
    paths:
      - $CI_PROJECT_DIR/TourGuide/build/reports/jacoco/test
      - $CI_PROJECT_DIR/TourGuide/build/jacocoHtml

javadoc:
  stage: documentation
  script: gradle javadoc
  artifacts:
    paths:
      - $CI_PROJECT_DIR/TourGuide/build/docs/javadoc