image: gradle:4.8.1-jdk8

stages:
  - build
  - test

cache:
  paths:
    - build
    - .gradle

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - cd TourGuide
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  script: gradle --build-cache bootJar
  artifacts:
    paths:
      - tourGuide-1.0.0.jar

test:
  stage: test
  script: gradle test
  artifacts:
    when: always
    paths:
      - rspec.xml
    reports:
      junit: rspec.xml 
     
