image: gradle:4.8.1-jdk8

stages:
  - build
  - test

cache:
  paths:
    - build
    - .gradle

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - cd TourGuide
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  script: ./gradlew --build-cache assemble
  artifacts:
    paths:
      - generatedFiles/*.jar
  only:
    - main

test:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    when: always
    reports:
      junit: generatedFiles/TEST-*.xml
