image: gradle:4.8.1-jdk8

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - cd TourGuide
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  script: gradle build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - $CI_PROJECT_DIR/build
      - $CI_PROJECT_DIR/.gradle

  artifacts:
    paths:
      - $CI_PROJECT_DIR/generatedFiles

test:
  stage: test
  script: gradle jacocoTestReport
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - $CI_PROJECT_DIR/build
      - $CI_PROJECT_DIR/.gradle

  artifacts:
    paths:
      - $CI_PROJECT_DIR/generatedFiles
